#!/usr/bin/env python3
"""Build the projects page from data/projects.yml.

Reads   data/projects.yml
Writes  _projects.md

Run after editing the YAML:

    python scripts/build_projects.py

Each project renders as a definition list — a plain label/value table, not a
card — which is what the design direction asks for. A row appears only when the
YAML has a value for it, so a grant with no published figure simply omits the
amount rather than showing an empty field.
"""

from __future__ import annotations

import html
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is missing. Install it with:  python3 -m pip install pyyaml")

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import warn_if_preview_running   # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "data" / "projects.yml"

# Order of rows within a project, and the label each field gets.
FIELDS = [
    ("funder", "Funder"),
    ("call", "Call"),
    ("reference", "Reference"),
    ("dates", "Dates"),
    ("amount", "Amount"),
    ("role", "Role"),
    ("note", "Note"),
]

warnings: list[str] = []


def esc(s) -> str:
    return html.escape(" ".join(str(s or "").split()), quote=False)


def render_project(p: dict, index: int, section: str) -> str:
    name, title = p.get("name"), p.get("title")
    if not name and not title:
        warnings.append(f"{section} entry {index + 1} has neither `name` nor `title`; skipped.")
        return ""

    # An acronym and a full title become one heading; either alone stands alone.
    if name and title:
        heading = (f'<span class="cbc-project-acronym">{esc(name)}</span>'
                   f'<span class="cbc-project-full">{esc(title)}</span>')
    else:
        heading = f'<span class="cbc-project-acronym">{esc(name or title)}</span>'

    rows = []
    for key, label in FIELDS:
        if p.get(key):
            rows.append(f"<dt>{label}</dt><dd>{esc(p[key])}</dd>")

    return ('<div class="cbc-project">'
            f'<h3 class="cbc-project-title">{heading}</h3>'
            + (f'<dl class="cbc-project-meta">{"".join(rows)}</dl>' if rows else "")
            + "</div>")


def render_section(items, section: str) -> str:
    blocks = [render_project(p, i, section) for i, p in enumerate(items)]
    blocks = [b for b in blocks if b]
    if not blocks:
        return ""
    return "```{=html}\n<div class=\"cbc-projects\">" + "".join(blocks) + "</div>\n```\n"


def main() -> None:
    if not CONFIG.exists():
        sys.exit(f"missing {CONFIG.relative_to(ROOT)}")
    cfg = yaml.safe_load(CONFIG.read_text())
    warn_if_preview_running(warnings)

    out = ["<!-- GENERATED by scripts/build_projects.py from data/projects.yml.\n"
           "     Hand edits will be overwritten. -->\n"]

    for key, heading in (("current", "Current"), ("completed", "Completed")):
        items = cfg.get(key) or []
        if not items:
            continue
        out.append(f"## {heading}\n")
        out.append(render_section(items, key))
        total = sum(1 for p in items if p.get("amount"))
        print(f"  {heading:<10} {len(items)} projects, {total} with a stated amount")

    res = cfg.get("resources") or {}
    if res.get("body"):
        out.append(f"## {esc(res.get('heading', 'Computational resources'))}\n")
        out.append(" ".join(str(res["body"]).split()) + "\n")

    for todo in (cfg.get("todos") or []):
        out.append("::: {.cbc-todo}\n" + " ".join(str(todo).split()) + "\n:::\n")

    (ROOT / "_projects.md").write_text("\n".join(out))

    # Quarto does not treat an include as a dependency for incremental renders.
    page = ROOT / "projects.qmd"
    if page.exists():
        page.touch()
        print("  touched projects.qmd so Quarto re-renders it")

    if warnings:
        print("\nWarnings:")
        for w in warnings:
            print(f"  ! {w}")
    print("\nWrote _projects.md.")


if __name__ == "__main__":
    main()
