#!/usr/bin/env python3
"""Build the research page from data/research.yml and the BibTeX exports.

Reads   data/research.yml   (the five areas, and which papers to feature)
        data/*.bib          (via build_publications, for the citations)
Writes  _research.md

Run after editing data/research.yml:

    python scripts/build_research.py

The BibTeX parsing, deduplication and author formatting are imported from
build_publications rather than reimplemented, so a citation on this page is
always identical to the same paper's entry on the publications page.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is missing. Install it with:  python3 -m pip install pyyaml")

import build_publications as bib
from _common import warn_if_preview_running

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "data" / "research.yml"
PUB_CONFIG = ROOT / "data" / "publications.yml"

warnings: list[str] = []


def load_publications():
    """Every deduplicated publication, keyed by DOI."""
    pub_cfg = yaml.safe_load(PUB_CONFIG.read_text())
    records = bib.load_records(pub_cfg)
    bib.apply_title_fixes(records, pub_cfg)
    records = [r for r in records if not bib.is_preprint(r)]
    records = bib.dedupe(records, "publications")
    return {r["doi"]: r for r in records if r["doi"]}, pub_cfg


def render_selected(entries, by_doi, matchers, area_title):
    """One area's selected papers.

    Title first, then the venue, then any note. An earlier version led with the
    note, but the notes available are paraphrases of the titles, so each entry
    read twice. The note now carries only what the title does not already say —
    corresponding authorship, a prize, a collaboration — and is omitted when
    there is nothing to add.
    """
    rows = []
    for e in entries:
        doi = bib.clean_doi(str(e.get("doi", "")))
        rec = by_doi.get(doi)
        if rec is None:
            warnings.append(f"{area_title}: no publication found for DOI {doi!r} — "
                            f"check it against data/*.bib. Nothing rendered for it.")
            continue
        note = " ".join(str(e.get("note", "")).split())
        venue = bib.venue(rec)
        rows.append(
            '<li class="cbc-sel">'
            + f'<span class="cbc-sel-title">{bib.esc(rec["title"])}</span>'
            + f'<span class="cbc-sel-cite">{venue}'
            + (f' <a class="cbc-pub-doi" href="https://doi.org/{rec["doi"]}">'
               f'doi.org/{rec["doi"]}</a>' if rec["doi"] else "")
            + "</span>"
            + (f'<span class="cbc-sel-note">{bib.esc(note)}</span>' if note else "")
            + "</li>"
        )
    if not rows:
        return ""
    return ('```{=html}\n<ol class="cbc-sels">' + "".join(rows) + "</ol>\n```\n")


def main() -> None:
    if not CONFIG.exists():
        sys.exit(f"missing {CONFIG.relative_to(ROOT)}")
    cfg = yaml.safe_load(CONFIG.read_text())

    warn_if_preview_running(warnings)
    warnings.extend(bib.warnings)
    bib.warnings.clear()

    print("Sources")
    by_doi, pub_cfg = load_publications()
    matchers = bib.build_member_matchers(pub_cfg)
    print(f"  {len(by_doi)} publications available by DOI\n")

    out = ["<!-- GENERATED by scripts/build_research.py from data/research.yml.\n"
           "     Hand edits will be overwritten. -->\n"]

    print("Areas")
    for area in cfg.get("areas", []):
        title = str(area["title"])
        body = " ".join(str(area.get("body", "")).split())
        selected = area.get("selected") or []
        # No numbering: these are parallel lines of work, not a sequence.
        out.append(f"## {title}\n")
        if body:
            out.append(f"{body}\n")
        block = render_selected(selected, by_doi, matchers, title)
        if block:
            out.append('::: {.cbc-side-label}\nSelected publications\n:::\n')
            out.append(block)
        if area.get("todo"):
            todo = " ".join(str(area["todo"]).split())
            out.append(f'::: {{.cbc-todo}}\n{todo}\n:::\n')
        print(f"  {title:<48} {len(selected)} selected"
              + ("  [TODO]" if area.get("todo") else ""))

    (ROOT / "_research.md").write_text("\n".join(out))

    # Quarto does not treat an include as a dependency for incremental renders.
    page = ROOT / "research.qmd"
    if page.exists():
        page.touch()
        print("\n  touched research.qmd so Quarto re-renders it")

    if warnings:
        print("\nWarnings:")
        for w in warnings:
            print(f"  ! {w}")
    print("\nWrote _research.md.")


if __name__ == "__main__":
    main()
