#!/usr/bin/env python3
"""Build the code-and-data page from data/software.yml.

Reads   data/software.yml
Writes  _software.md

Run after editing the YAML:

    python scripts/build_software.py

The page is deliberately near-empty for now: an explanatory sentence and a link
to the GitHub organization. The machinery exists so that adding a repository
later is a few lines of YAML rather than a layout change — the same pattern as
the publications, team and projects pages.
"""

from __future__ import annotations

import html
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is missing. Install it with:  python3 -m pip install pyyaml")

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import warn_if_preview_running   # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "data" / "software.yml"

warnings: list[str] = []


def esc(s) -> str:
    return html.escape(" ".join(str(s or "").split()), quote=False)


def render_entry(e: dict, index: int) -> str:
    if not e.get("title") or not e.get("url"):
        warnings.append(f"entry {index + 1} needs both `title` and `url`; skipped.")
        return ""
    bits = ['<li class="cbc-repo">']
    bits.append(f'<a class="cbc-repo-title" href="{esc(e["url"])}">{esc(e["title"])}</a>')
    if e.get("kind"):
        bits.append(f'<span class="cbc-repo-kind">{esc(e["kind"])}</span>')
    if e.get("description"):
        bits.append(f'<span class="cbc-repo-desc">{esc(e["description"])}</span>')
    meta = []
    if e.get("paper"):
        doi = esc(e["paper"])
        meta.append(f'Supports <a href="https://doi.org/{doi}">doi.org/{doi}</a>')
    if e.get("licence"):
        meta.append(f'{esc(e["licence"])} licence')
    if meta:
        bits.append(f'<span class="cbc-repo-meta">{" · ".join(meta)}</span>')
    bits.append("</li>")
    return "".join(bits)


def main() -> None:
    if not CONFIG.exists():
        sys.exit(f"missing {CONFIG.relative_to(ROOT)}")
    cfg = yaml.safe_load(CONFIG.read_text()) or {}
    warn_if_preview_running(warnings)

    out = ["<!-- GENERATED by scripts/build_software.py from data/software.yml.\n"
           "     Hand edits will be overwritten. -->\n"]

    if cfg.get("intro"):
        out.append(":::: {.cbc-lead-plain}\n"
                   + " ".join(str(cfg["intro"]).split()) + "\n::::\n")

    entries = [e for e in (cfg.get("entries") or [])]
    if entries:
        rows = [render_entry(e, i) for i, e in enumerate(entries)]
        rows = [r for r in rows if r]
        out.append("```{=html}\n<ul class=\"cbc-repos\">" + "".join(rows) + "</ul>\n```\n")
        print(f"  {len(rows)} entries")
    else:
        print("  no entries yet — rendering the intro and the GitHub link only")

    if cfg.get("github"):
        url = esc(cfg["github"])
        label = url.replace("https://", "")
        out.append(f'[{label}]({url})\n')

    (ROOT / "_software.md").write_text("\n".join(out))

    # Quarto does not treat an include as a dependency for incremental renders.
    page = ROOT / "code-and-data.qmd"
    if page.exists():
        page.touch()
        print("  touched code-and-data.qmd so Quarto re-renders it")

    if warnings:
        print("\nWarnings:")
        for w in warnings:
            print(f"  ! {w}")
    print("\nWrote _software.md.")


if __name__ == "__main__":
    main()
