#!/usr/bin/env python3
"""Build the team page from data/team.yml.

Reads   data/team.yml
Writes  _team.md

Run after editing the YAML:

    python scripts/build_team.py

Portraits come from assets/images/people/<slug>.jpg, generated by
scripts/build_images.py. A member whose portrait is missing gets a
correctly-sized placeholder box — never a stock photo, and never an
AI-generated one.
"""

from __future__ import annotations

import html
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is missing. Install it with:  python3 -m pip install pyyaml")

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import warn_if_preview_running   # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "data" / "team.yml"
PORTRAITS = ROOT / "assets" / "images" / "people"

warnings: list[str] = []


def esc(s) -> str:
    return html.escape(" ".join(str(s or "").split()), quote=False)


# Portraits are 4:5, matching data/images.yml -> defaults.portrait_aspect.
PORTRAIT_ASPECT = 0.8


def portrait(slug: str, name: str, px: int) -> str:
    """An <img> at the given width, or a placeholder box of the same footprint.

    The width/height attributes carry the real 4:5 ratio so the browser reserves
    the right space and the page does not shift as the images load.
    """
    ph = round(px / PORTRAIT_ASPECT)
    one = PORTRAITS / f"{slug}.jpg"
    two = PORTRAITS / f"{slug}@2x.jpg"
    if not one.exists():
        warnings.append(f"no portrait for {name} — expected "
                        f"assets/images/people/{slug}.jpg. A placeholder box is "
                        f"shown; add the photo to assets/images/_originals/people/ "
                        f"and re-run scripts/build_images.py.")
        return (f'<div class="cbc-portrait cbc-placeholder" '
                f'style="width:{px}px;height:{ph}px" role="img" '
                f'aria-label="No photograph of {esc(name)} yet">Photo to come</div>')
    src = f"assets/images/people/{slug}.jpg"
    srcset = f"{src} 1x, assets/images/people/{slug}@2x.jpg 2x" if two.exists() else src
    return (f'<img class="cbc-portrait" src="{src}" srcset="{srcset}" '
            f'width="{px}" height="{ph}" alt="{esc(name)}" loading="lazy">')


def render_pi(pi: dict) -> str:
    bits = [f'<div class="cbc-pi-card">']
    bits.append(portrait(str(pi["slug"]), str(pi["name"]), 180))
    bits.append('<div class="cbc-pi-detail">')
    bits.append(f'<h3 class="cbc-person-name">{esc(pi["name"])}</h3>')
    bits.append(f'<p class="cbc-person-role">{esc(pi.get("role"))}</p>')
    if pi.get("bio"):
        bits.append(f'<p class="cbc-person-bio">{esc(pi["bio"])}</p>')

    if pi.get("interests"):
        bits.append('<p class="cbc-person-sub">Research interests</p>')
        bits.append('<ul class="cbc-person-list">'
                    + "".join(f"<li>{esc(i)}</li>" for i in pi["interests"])
                    + "</ul>")
    contact = []
    if pi.get("email"):
        e = esc(pi["email"])
        contact.append(f'<a href="mailto:{e}">{e}</a>')
    for link in (pi.get("links") or []):
        contact.append(f'<a href="{esc(link["url"])}">{esc(link["label"])}</a>')
    if contact:
        bits.append('<p class="cbc-person-contact">' + " ".join(contact) + "</p>")

    bits.append("</div></div>")
    return "".join(bits)


def render_member(m: dict) -> str:
    """One card in the four-per-row grid: portrait, then details beneath it."""
    bits = ['<li class="cbc-member">']
    bits.append(portrait(str(m["slug"]), str(m["name"]), 222))
    bits.append('<div class="cbc-member-detail">')
    bits.append(f'<span class="cbc-person-name">{esc(m["name"])}</span>')
    bits.append(f'<span class="cbc-person-role">{esc(m.get("role"))}</span>')
    if m.get("note"):
        bits.append(f'<span class="cbc-member-note">{esc(m["note"])}</span>')
    if m.get("topic"):
        bits.append(f'<span class="cbc-member-topic">{esc(m["topic"])}</span>')
    if m.get("funding"):
        bits.append(f'<span class="cbc-member-funding">{esc(m["funding"])}</span>')
    if m.get("email"):
        e = esc(m["email"])
        bits.append(f'<span class="cbc-member-mail"><a href="mailto:{e}">{e}</a></span>')
    bits.append("</div></li>")
    return "".join(bits)


def main() -> None:
    if not CONFIG.exists():
        sys.exit(f"missing {CONFIG.relative_to(ROOT)}")
    cfg = yaml.safe_load(CONFIG.read_text())
    warn_if_preview_running(warnings)

    out = ["<!-- GENERATED by scripts/build_team.py from data/team.yml.\n"
           "     Hand edits will be overwritten. -->\n"]

    gp = cfg.get("group_photo") or {}
    if gp.get("src"):
        path = ROOT / str(gp["src"])
        if path.exists():
            two = str(gp["src"]).replace(".jpg", "@2x.jpg")
            srcset = (f'{gp["src"]} 1x, {two} 2x'
                      if (ROOT / two).exists() else str(gp["src"]))
            out.append("```{=html}\n"
                       f'<figure class="cbc-groupphoto">'
                       f'<img src="{gp["src"]}" srcset="{srcset}" '
                       f'alt="{esc(gp.get("alt"))}"></figure>\n```\n')
        else:
            warnings.append(f"group photo missing: {gp['src']}")

    pis = cfg.get("pis") or []
    if pis:
        out.append("## Principal investigators\n")
        out.append("```{=html}\n<div class=\"cbc-pi-pair-full\">"
                   + "".join(render_pi(p) for p in pis) + "</div>\n```\n")
        print(f"  {len(pis)} principal investigators")

    members = cfg.get("members") or []
    if members:
        out.append("## Researchers and students\n")
        out.append("```{=html}\n<ul class=\"cbc-members\">"
                   + "".join(render_member(m) for m in members) + "</ul>\n```\n")
        print(f"  {len(members)} researchers and students")

    alumni = cfg.get("alumni") or []
    if alumni:
        out.append("## Alumni\n")
        rows = []
        for a in alumni:
            line = f'<span class="cbc-person-name">{esc(a["name"])}</span>'
            if a.get("was"):
                line += f'<span class="cbc-member-funding">{esc(a["was"])}</span>'
            if a.get("now"):
                line += f'<span class="cbc-member-topic">{esc(a["now"])}</span>'
            rows.append(f'<li class="cbc-alumnus">{line}</li>')
        out.append("```{=html}\n<ul class=\"cbc-alumni\">" + "".join(rows) + "</ul>\n```\n")
        print(f"  {len(alumni)} alumni")

    for todo in (cfg.get("todos") or []):
        out.append("::: {.cbc-todo}\n" + " ".join(str(todo).split()) + "\n:::\n")

    (ROOT / "_team.md").write_text("\n".join(out))

    # Quarto does not treat an include as a dependency for incremental renders.
    page = ROOT / "team.qmd"
    if page.exists():
        page.touch()
        print("  touched team.qmd so Quarto re-renders it")

    if warnings:
        print("\nWarnings:")
        for w in warnings:
            print(f"  ! {w}")
    print("\nWrote _team.md.")


if __name__ == "__main__":
    main()
